### ISSUE TITLE
Remove porcelain dependency?

### ISSUE THREAD

**Issue by hugomaiavieira** [hugomaiavieira/elixir-pdf-generator#1]
The `porcelain` package [is not been maintained very well](https://github.com/alco/porcelain/issues/50), has [knowing design flaws that can lead into zombie processes](https://github.com/alco/porcelain/issues/50#issuecomment-401462266), and is showing some [deprecation warnings](https://github.com/alco/porcelain/issues/45) on compilation.

Removing it will make this package dependency free (besides `wkhtmltopdf` of course). Also it will solve [the hot code upgrading using distillery issue](https://github.com/gutschilla/elixir-pdf-generator/issues/33).

There is a specific reason to use `porcelain`? Couldn't we use the built in [`System.cmd/3`](https://hexdocs.pm/elixir/1.7.2/System.html#cmd/3) function?

**TODO**: read more about [`Port`](https://hexdocs.pm/elixir/1.7.2/Port.html) module, the [zombie processes](https://hexdocs.pm/elixir/1.7.2/Port.html#module-zombie-os-processes), and the [porcelain's basic driver](https://github.com/alco/porcelain/blob/master/lib/porcelain/drivers/basic_driver.ex) to try to answer the questions above and create an issue on the original repo.

**Comment by gutschilla** [comment]
# Excuses

@hugomaiavieira You're right about Porcelain. Back in 2015, when this module came to life, Porcelain was the easiest way to get something started without needing to dig into the ports (The documentation was, well, like this: https://hexdocs.pm/elixir/1.0.5/Port.html#summary). Initially, I didn't want to use temporary files – but then I got it trivially easy working with so I kept it that way.

# The bright future

I guess, Ports will do. Just need time to do it ;-)

**Comment by hugomaiavieira** [comment]
Thanks for the info @gutschilla! :)

**Comment by hugomaiavieira** [comment]
https://github.com/gutschilla/elixir-pdf-generator/issues/44
